export const headers = [
    {title: 'Name', align: 'start', sortable: false, key: 'name',},
    {title: 'Description', key: 'description', align: 'start', sortable: false},
    {title: 'Difficulty', key: 'difficulty', align: 'start', sortable: false},
    {title: 'Category', key: 'category', align: 'start', sortable: false},
    {title: 'Made by', key: 'made_by', align: 'start', sortable: false},
    {title: 'Actions', key: 'actions', align: 'start', sortable: false},
    {title: 'Classes', key: 'classes', align: 'center', sortable: false},
]

export const modules = [
    {
        id: '2cccd034-9900-11ee-b9d1-0242ac120002',
        name: 'Module Grammatica A1',
        description: 'This is a module description.',
        difficulty: 'A1',
        category: 'Grammatica',
        made_by: 'Toon Otten',
    },
    {
        id: '2cccd034-9900-11ee-b9d1-0242ac120002',
        name: 'Module Grammatica A2',
        description: 'This is a module description.',
        difficulty: 'A2',
        category: 'Grammatica',
        made_by: 'Toon Otten',
    },
    {
        id: '2cccd034-9900-11ee-b9d1-0242ac120002',
        name: 'Module Grammatica B1',
        description: 'This is a module description.',
        difficulty: 'B1',
        category: 'Grammatica',
        made_by: 'Toon Otten',
    },
    {
        id: '2cccd034-9900-11ee-b9d1-0242ac120002',
        name: 'Module Grammatica B2',
        description: 'This is a module description.',
        difficulty: 'B2',
        category: 'Grammatica',
        made_by: 'Toon Otten',
    },
    {
        id: '2cccd034-9900-11ee-b9d1-0242ac120002',
        name: 'Module Grammatica C1',
        description: 'This is a module description.',
        difficulty: 'C1',
        category: 'Grammatica',
        made_by: 'Toon Otten',
    }, {
        id: '2cccd034-9900-11ee-b9d1-0242ac120002',
        name: 'Module Grammatica C2',
        description: 'This is a module description.',
        difficulty: 'C2',
        category: 'Grammatica',
        made_by: 'Toon Otten',
    }, {
        id: '2cccd034-9900-11ee-b9d1-0242ac120002',
        name: 'Module Grammatica C2+',
        description: 'This is a module description.',
        difficulty: 'C2',
        category: 'Grammatica',
        made_by: 'Toon Otten',
    },
    {
        id: '2cccd034-9900-11ee-b9d1-0242ac120002',
        name: 'Module Grammatica C2++',
        description: 'This is a module description.',
        difficulty: 'C2',
        category: 'Grammatica',
        made_by: 'Toon Otten',
    },
    {
        id: '2cccd034-9900-11ee-b9d1-0242ac120002',
        name: 'Module Grammatica Mixed',
        description: 'This is a module description.',
        difficulty: 'Fastlane',
        category: 'Grammatica',
        made_by: 'Toon Otten',
    },
    {
        id: '2cccd034-9900-11ee-b9d1-0242ac120002',
        name: 'Module Grammatica Mixed',
        description: 'This is a module description.',
        difficulty: 'Fastlane',
        category: 'Grammatica',
        made_by: 'Toon Otten',
    },
]