package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"example/graph/model"
)

// TopCustomers is the resolver for the topCustomers field.
func (r *queryResolver) TopCustomers(ctx context.Context, first *int) ([]*model.Customer, error) {
	r.customers = append(r.customers, &model.Customer{ID: "test-id", Name: "test-name", Email: "test@email"})

	return r.customers, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
