# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenaiActions.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13OpenaiActions.proto\x12\x05proto\"!\n\nKeyRequest\x12\x13\n\x0b\x62\x65\x61rerToken\x18\x01 \x01(\t\")\n\x0bKeyResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2@\n\rSchoolService\x12/\n\x06GetKey\x12\x11.proto.KeyRequest\x1a\x12.proto.KeyResponseB\x05Z\x03/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OpenaiActions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\003/pb'
  _globals['_KEYREQUEST']._serialized_start=30
  _globals['_KEYREQUEST']._serialized_end=63
  _globals['_KEYRESPONSE']._serialized_start=65
  _globals['_KEYRESPONSE']._serialized_end=106
  _globals['_SCHOOLSERVICE']._serialized_start=108
  _globals['_SCHOOLSERVICE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
