// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Class struct {
	ID          string  `json:"id"`
	ModuleID    string  `json:"module_Id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Difficulty  *int    `json:"difficulty,omitempty"`
	CreatedAt   *string `json:"created_at,omitempty"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
	SoftDeleted *bool   `json:"soft_deleted,omitempty"`
}

type ClassInput struct {
	ModuleID    string  `json:"module_Id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Difficulty  *int    `json:"difficulty,omitempty"`
}
