{
 "title": "Language Fitness Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   { "name": "service", "label": "Service", "query": "label_values(service)" },
   { "name": "pod", "label": "Pod", "query": "label_values(pod)" },
   { "name": "endpoint", "label": "Endpoint", "query": "label_values(endpoint)" },
   { "name": "outcome", "label": "ResponseStatus", "query": "label_values(outcome)" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU  Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage {endpoint=~\"$endpoint\",service=~\"$service\",pod=~\"$pod\",namespace=~\"$namespace\", uri!~\".*actuator.*\"}"
    },
    {
     "expr": "process_cpu_usage {endpoint=~\"$endpoint\",service=~\"$service\",pod=~\"$pod\",namespace=~\"$namespace\", uri!~\".*actuator.*\"}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{endpoint=~\"$endpoint\",service=~\"$service\",pod=~\"$pod\",namespace=~\"$namespace\"}"
    },
    {
     "expr": "system_cpu_count{endpoint=~\"$endpoint\",service=~\"$service\",pod=~\"$pod\",namespace=~\"$namespace\"}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count {endpoint=~\"$endpoint\",service=~\"$service\",pod=~\"$pod\",namespace=~\"$namespace\",exception=\"None\", uri!~\".*actuator.*\"}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{endpoint=~\"$endpoint\",service=~\"$service\",pod=~\"$pod\",namespace=~\"$namespace\",outcome=~\"$outcome\",exception=\"None\", uri!~\".*actuator.*\"}/ http_server_requests_seconds_count{endpoint=~\"$endpoint\",service=~\"$service\",pod=~\"$pod\",namespace=~\"$namespace\",outcome=~\"$outcome\", exception=\"None\", uri!~\".*actuator.*\"}"
    }
   ]
  }
 ]
}