package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"ExerciseMicroservice/graph/model"
	"context"
	"fmt"
)

// AddExercise is the resolver for the AddExercise field.
func (r *mutationResolver) AddExercise(ctx context.Context, exercise model.ExerciseInput) (*model.Exercise, error) {
	panic(fmt.Errorf("not implemented: AddExercise - AddExercise"))
}

// UpdateExercise is the resolver for the UpdateExercise field.
func (r *mutationResolver) UpdateExercise(ctx context.Context, exercise model.ExerciseInput) (*model.Exercise, error) {
	panic(fmt.Errorf("not implemented: UpdateExercise - UpdateExercise"))
}

// DeleteExercise is the resolver for the DeleteExercise field.
func (r *mutationResolver) DeleteExercise(ctx context.Context, id string) (*model.Exercise, error) {
	panic(fmt.Errorf("not implemented: DeleteExercise - DeleteExercise"))
}

// GetExerciseByModuleID is the resolver for the GetExerciseByModuleId field.
func (r *queryResolver) GetExerciseByModuleID(ctx context.Context, moduleID string) ([]*model.Exercise, error) {
	panic(fmt.Errorf("not implemented: GetExerciseByModuleID - GetExerciseByModuleId"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
