package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"example/graph/model"
)

// CreateClass is the resolver for the createClass field.
func (r *mutationResolver) CreateClass(ctx context.Context, input model.ClassInput) (*model.Class, error) {
	//headers := ctx.Value("headers").(http.Header)
	//
	//// Access tokens from the headers, e.g., for Bearer token
	//accessToken := headers.Get("Authorization")

	class, err := r.Service.CreateClass(input)
	if err != nil {
		return nil, err
	}

	return class, nil
}

// UpdateClass is the resolver for the updateClass field.
func (r *mutationResolver) UpdateClass(ctx context.Context, id string, input model.ClassInput) (*model.Class, error) {
	class, err := r.Service.UpdateClass(id, input)
	if err != nil {
		return nil, err
	}

	return class, nil
}

// DeleteClass is the resolver for the deleteClass field.
func (r *mutationResolver) DeleteClass(ctx context.Context, id string) (*string, error) {
	err := r.Service.DeleteClass(id)
	if err != nil {
		return nil, err
	}

	return &id, nil
}

// GetClass is the resolver for the getClass field.
func (r *queryResolver) GetClass(ctx context.Context, id string) (*model.Class, error) {
	class, err := r.Service.GetClassById(id)
	if err != nil {
		return nil, err
	}

	return class, nil
}

// ListClasses is the resolver for the listClasses field.
func (r *queryResolver) ListClasses(ctx context.Context) ([]*model.Class, error) {
	// Retrieve a list of all modules using the repository.
	classes, err := r.Service.ListClasses()
	if err != nil {
		return nil, err
	}

	return classes, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
