// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Class struct {
	ID          string  `json:"id"`
	ModuleID    string  `json:"module_Id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Difficulty  float64 `json:"difficulty"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	SoftDeleted bool    `json:"soft_deleted"`
}

type Exercise struct {
	ID             string  `json:"id"`
	ClassID        string  `json:"class_Id"`
	Name           string  `json:"name"`
	Question       string  `json:"question"`
	Answer         string  `json:"answer"`
	QuestionTypeID string  `json:"question_type_id"`
	Difficulty     float64 `json:"difficulty"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
	SoftDeleted    bool    `json:"soft_deleted"`
}

type LeaderboardRow struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Rating   int    `json:"rating"`
	Position int    `json:"position"`
}

type Module struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Difficulty  float64 `json:"difficulty"`
	Category    string  `json:"category"`
	MadeBy      string  `json:"made_by"`
	Private     bool    `json:"private"`
	Key         string  `json:"key"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	SoftDeleted bool    `json:"soft_deleted"`
}

type NewResult struct {
	ExerciseID string `json:"exercise_id"`
	UserID     string `json:"user_id"`
	ClassID    string `json:"class_id"`
	ModuleID   string `json:"module_id"`
	Input      string `json:"input"`
	Result     string `json:"result"`
}

type Result struct {
	ID          string `json:"id"`
	ExerciseID  string `json:"exercise_id"`
	UserID      string `json:"user_id"`
	ClassID     string `json:"class_id"`
	ModuleID    string `json:"module_id"`
	Input       string `json:"input"`
	Result      string `json:"result"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
	SoftDeleted bool   `json:"soft_deleted"`
}
