{
 "title": "Language Fitness Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Microservices",
    "query": "gandalf-the-gateway,\nexercise-microservice, class-microservice, module-microservice, result-microservice, school-microservice, openai-microservice, saga-microservice"
   }
  ]
 },
 "panels": [
  {
   "title": "Amount Running Pods ($Microservices)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{exported_namespace=\"bramterlouw-dev\", exported_container=\"$Microservices\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage ($Microservices)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{exported_namespace=\"bramterlouw-dev\", container=\"$Microservices\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RAM Usage ($Microservices)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{exported_namespace=\"bramterlouw-dev\", container=\"$Microservices\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Requests ($Microservices)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_requests_total{namespace=\"bramterlouw-dev\", container=\"$Microservices\", method=\"POST\", handler=\"/query\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}