// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Module struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Difficulty  *int    `json:"difficulty,omitempty"`
	Category    *string `json:"category,omitempty"`
	MadeBy      *string `json:"made_by,omitempty"`
	Private     *bool   `json:"private,omitempty"`
	Key         *string `json:"key,omitempty"`
	CreatedAt   *string `json:"created_at,omitempty"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
	SoftDeleted *bool   `json:"soft_deleted,omitempty"`
}

type ModuleInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Difficulty  *int    `json:"difficulty,omitempty"`
	Category    *string `json:"category,omitempty"`
	MadeBy      *string `json:"made_by,omitempty"`
	Private     *bool   `json:"private,omitempty"`
	Key         *string `json:"key,omitempty"`
}
