package integration

import (
	"encoding/json"
	"fmt"
	"github.com/99designs/gqlgen/client"
	"github.com/stretchr/testify/assert"
	"school/test/integration/helper"
	"school/test/integration/requests"
	r "school/test/integration/responses"
	"strings"
	"testing"
)

var Token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuMzNESXZyQUZ0b1JGQ1d2UTMyOF85bXpjeU5JbXptZ1NSNFVKM05rdEdRIn0.eyJleHAiOjE3MDUzMjg1NzQsImlhdCI6MTcwNTMyNzY3NCwianRpIjoiZTE2ODJjMjktZjczZC00NDdiLWEwNzYtMzhmN2U4YWZhZGVmIiwiaXNzIjoiaHR0cHM6Ly9leGFtcGxlLWtleWNsb2FrLWJyYW10ZXJsb3V3LWRldi5hcHBzLm9jcDItaW5ob2xsYW5kLmpvcmFuLWJlcmdmZWxkLmNvbS9yZWFsbXMvY2xvdWQtcHJvamVjdCIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwidXNlci1tYW5hZ2VtZW50LWNsaWVudCIsImFjY291bnQiXSwic3ViIjoiNmMxY2U0NDgtNjcwZi00N2IyLTgzZjctNGQ3NzFiMDE3NzViIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibG9naW4tY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6IjdiMTU0YzRhLTgwMjgtNDFiYi1hNmFmLTkwNGM2MGQ0YzEwZSIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1jbG91ZC1wcm9qZWN0Iiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsibWFuYWdlLXVzZXJzIiwidmlldy11c2VycyIsInF1ZXJ5LWdyb3VwcyIsInF1ZXJ5LXVzZXJzIl19LCJ1c2VyLW1hbmFnZW1lbnQtY2xpZW50Ijp7InJvbGVzIjpbImZpbHRlcl9yZXN1bHRfc29mdERlbGV0ZSIsImZpbHRlcl9jbGFzc19kaWZmaWN1bHR5IiwiZmlsdGVyX2V4ZXJjaXNlX2RpZmZpY3VsdHkiLCJmaWx0ZXJfc2Nob29sX25hbWUiLCJ1cGRhdGVfcmVzdWx0IiwiZmlsdGVyX2V4ZXJjaXNlX21vZHVsZV9pZCIsImZpbHRlcl9tb2R1bGVfY2F0ZWdvcnkiLCJkZWxldGVfbW9kdWxlX2FsbCIsImNyZWF0ZV9leGVyY2lzZSIsImdldF9zY2hvb2wiLCJmaWx0ZXJfc2Nob29sX2xvY2F0aW9uIiwiZmlsdGVyX21vZHVsZV9kaWZmaWN1bHR5IiwiZmlsdGVyX3Jlc3VsdF9tb2R1bGVfaWQiLCJvcGVuYWlfZ2VuZXJhdGVfcXVlc3Rpb25zIiwiZ2V0X21vZHVsZSIsImdldF9tb2R1bGVzIiwiZmlsdGVyX3NjaG9vbF9zb2Z0RGVsZXRlIiwiZGVsZXRlX3Jlc3VsdF9hbGwiLCJ1cGRhdGVfbW9kdWxlX2FsbCIsImZpbHRlcl9jbGFzc19tb2R1bGVfaWQiLCJjcmVhdGVfcmVzdWx0IiwiZ2V0X3Jlc3VsdF9hbGwiLCJmaWx0ZXJfbW9kdWxlX21hZGVfYnkiLCJsaXN0X3Jlc3VsdHNfYWxsIiwiZmlsdGVyX2V4ZXJjaXNlX3F1ZXN0aW9uX3R5cGVfaWQiLCJ1cGRhdGVfY2xhc3NfYWxsIiwiZ2V0X2NsYXNzIiwiZ2V0X3NjaG9vbHNfYWxsIiwiZmlsdGVyX3Jlc3VsdF9leGVyY2lzZV9pZCIsImZpbHRlcl9jbGFzc19zb2Z0RGVsZXRlIiwidXBkYXRlX3Jlc3VsdF9hbGwiLCJvcGVuYWlfZ2VuZXJhdGVfcXVlc3Rpb25zX2Zyb21fZmlsZSIsImdldF9jbGFzc2VzX2FsbCIsInVwZGF0ZV9zY2hvb2wiLCJmaWx0ZXJfc2Nob29sX21hZGVfYnkiLCJnZXRfZXhlcmNpc2VzX2FsbCIsIm9wZW5haV9nZW5lcmF0ZV9leHBsYW5hdGlvbiIsImZpbHRlcl9jbGFzc19tYWRlX2J5IiwiZmlsdGVyX21vZHVsZV9zb2Z0RGVsZXRlIiwiZ2V0X2V4ZXJjaXNlcyIsImdldF9jbGFzc2VzIiwiZGVsZXRlX21vZHVsZSIsImdldF9zY2hvb2xzIiwiZGVsZXRlX2V4ZXJjaXNlIiwidXBkYXRlX2V4ZXJjaXNlIiwiZ2V0X2V4ZXJjaXNlIiwiZmlsdGVyX3Jlc3VsdF91c2VyX2lkIiwiZmlsdGVyX2V4ZXJjaXNlX25hbWUiLCJmaWx0ZXJfZXhlcmNpc2Vfc29mdERlbGV0ZSIsImRlbGV0ZV9leGVyY2lzZV9hbGwiLCJmaWx0ZXJfcmVzdWx0X2NsYXNzX2lkIiwidXBkYXRlX3NjaG9vbF9hbGwiLCJkZWxldGVfY2xhc3MiLCJkZWxldGVfcmVzdWx0IiwiY3JlYXRlX21vZHVsZSIsInVwZGF0ZV9leGVyY2lzZV9hbGwiLCJjcmVhdGVfY2xhc3MiLCJjcmVhdGVfc2Nob29sIiwiZ2V0X21vZHVsZXNfYWxsIiwiZmlsdGVyX2V4ZXJjaXNlX2NsYXNzX2lkIiwibGlzdF9yZXN1bHRzIiwiZmlsdGVyX21vZHVsZV9zY2hvb2xfaWQiLCJmaWx0ZXJfY2xhc3NfbmFtZSIsImdldF9yZXN1bHQiLCJmaWx0ZXJfc2Nob29sX2hhc19vcGVuYWlfYWNjZXNzIiwib3BlbmFpX2dldF9zY2hvb2wiLCJ1cGRhdGVfbW9kdWxlIiwiZmlsdGVyX21vZHVsZV9uYW1lIiwiZmlsdGVyX21vZHVsZV9tYWRlX2J5X25hbWUiLCJmaWx0ZXJfZXhlcmNpc2VfbWFkZV9ieSIsImRlbGV0ZV9zY2hvb2xfYWxsIiwidXBkYXRlX2NsYXNzIiwiZmlsdGVyX21vZHVsZV9wcml2YXRlIiwiZGVsZXRlX2NsYXNzX2FsbCJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiN2IxNTRjNGEtODAyOC00MWJiLWE2YWYtOTA0YzYwZDRjMTBlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiY2hhZCBhZG1pbiIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImdpdmVuX25hbWUiOiJjaGFkIiwiZmFtaWx5X25hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIn0.aP3CxWp024Ob2xmw-Jk6rNzA5wldN_Zq3ukCXT5aazEtp3_0PiBV8olkKIVWw2DwAQd3o6rGhstqfLhoNobkKtN58633LI8QMd3eLI8TaYMlOmhbYRft7OTkKIDpSx-J9-8FdjkkaumJwvcQ3IH2ME-GD4e0nSJNjUdrRYYCiNSRDRfSb8rtikDVCH4DtLZUE5UmSZEftcdJsG74iOO_Tr91H__T0pjKhgn2o4DFgaqvA__CGfeYjN0NkT8It8ETYf4xEoNCc0Ey3VkvK9ifMZJkl0sjB7NqlIHUxFT_OgImmXZP0lG0rh25BV5h8MxnhljcYe5TQwUB5WUhG41D-g"

var StudentToken = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuMzNESXZyQUZ0b1JGQ1d2UTMyOF85bXpjeU5JbXptZ1NSNFVKM05rdEdRIn0.eyJleHAiOjE3MDQzNzg1MzIsImlhdCI6MTcwNDM3ODIzMiwianRpIjoiOTVmMDVhYjItNmM4Yy00YTFjLWEwYjEtNDlhM2M3ZWYyMTc3IiwiaXNzIjoiaHR0cHM6Ly9leGFtcGxlLWtleWNsb2FrLWJyYW10ZXJsb3V3LWRldi5hcHBzLm9jcDItaW5ob2xsYW5kLmpvcmFuLWJlcmdmZWxkLmNvbS9yZWFsbXMvY2xvdWQtcHJvamVjdCIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwidXNlci1tYW5hZ2VtZW50LWNsaWVudCIsImFjY291bnQiXSwic3ViIjoiM2U4MDVlOTctZmM3Ni00MzI0LWExOTktNDYzZjYwZTQzYjQ0IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibG9naW4tY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6IjVhMGJlMTY5LWQyNzctNDgwNC1iNjlmLWQzMTNjZDMxOTIwYiIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1jbG91ZC1wcm9qZWN0Iiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy11c2VycyIsInF1ZXJ5LWdyb3VwcyIsInF1ZXJ5LXVzZXJzIl19LCJ1c2VyLW1hbmFnZW1lbnQtY2xpZW50Ijp7InJvbGVzIjpbImdldF9leGVyY2lzZSIsImdldF9tb2R1bGUiLCJnZXRfbW9kdWxlcyIsImZpbHRlcl9tb2R1bGVfbWFkZV9ieV9uYW1lIiwiZ2V0X2NsYXNzIiwiZ2V0X2V4ZXJjaXNlcyIsImZpbHRlcl9leGVyY2lzZV9jbGFzc19pZCIsImdldF9jbGFzc2VzIiwiZmlsdGVyX21vZHVsZV9zY2hvb2xfaWQiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInNpZCI6IjVhMGJlMTY5LWQyNzctNDgwNC1iNjlmLWQzMTNjZDMxOTIwYiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6Ik1lcmxpam4gQnVzY2giLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtZXJsaWpuQHN0dWRlbnQuY29tIiwiZ2l2ZW5fbmFtZSI6Ik1lcmxpam4iLCJmYW1pbHlfbmFtZSI6IkJ1c2NoIiwiZW1haWwiOiJtZXJsaWpuQHN0dWRlbnQuY29tIn0.InwXY-fwpicRpoij63WHz3arsIfdQ-pyn-EPCARUWbYHSrJ1FVkw1Kb2Ea3-2zwg56K4hveidofESHBTQEIcGmpC0qRgdOyNGnPgE6Wt6xYkhdhGYlvYbvWg9F3dMmDtaTq_PBASYGrz7Cr38IZEI6IaTo4zzLpAWPSwkKpJZyohbGnq_bPWQOYCbjUVYS63INwqGCha_lO97WW1h5iONEtX4XjWH43MAIp9sH-TXrdpnFa2tVwNwLl8qz_bunoWAZb1l_Fde_VTt2plGJQWVDF3vnGN3kRjB84GpPSiyPFBK8Jj9f7mmkOi9VO-56yQRfmyScoq2-qcd_SQmO23OQ"

func TestResolver_CreateSchool(t *testing.T) {
	fmt.Println("\nRunning TestResolver_CreateSchool")
	c := helper.CreateClient()

	t.Run("Create school", func(t *testing.T) {

		c.MustPost(
			requests.CreateSchoolMutation,
			&r.CreateSchoolResponse,
			client.Var("input", requests.GenerateSchoolInput()),
			helper.AddContext(Token),
		)

		assert.NotEmpty(t, r.CreateSchoolResponse)
		assert.NotEmpty(t, r.CreateSchoolResponse.CreateSchool.ID)
		assert.Equal(t, requests.Name, r.CreateSchoolResponse.CreateSchool.Name)
		assert.Equal(t, requests.Location, r.CreateSchoolResponse.CreateSchool.Location)
		assert.Equal(t, requests.HasOpenaiAccess, r.CreateSchoolResponse.CreateSchool.HasOpenaiAccess)
		assert.Equal(t, requests.OpenAIKey, r.CreateSchoolResponse.CreateSchool.OpenaiKey)
	})
}

func TestResolver_CreateSchool_NoOpenAiAccess(t *testing.T) {
	fmt.Println("\nRunning TestResolver_CreateSchool_NoOpenAiAccess")
	c := helper.CreateClient()

	t.Run("Create school", func(t *testing.T) {

		c.MustPost(
			requests.CreateSchoolMutation,
			&r.CreateSchoolResponse,
			client.Var("input", requests.GenerateSchoolInputNoAccess()),
			helper.AddContext(Token),
		)

		assert.NotEmpty(t, r.CreateSchoolResponse)
		assert.NotEmpty(t, r.CreateSchoolResponse.CreateSchool.ID)
		assert.Equal(t, requests.Name, r.CreateSchoolResponse.CreateSchool.Name)
		assert.Equal(t, requests.Location, r.CreateSchoolResponse.CreateSchool.Location)
		assert.Equal(t, false, r.CreateSchoolResponse.CreateSchool.HasOpenaiAccess)
		assert.Equal(t, "", r.CreateSchoolResponse.CreateSchool.OpenaiKey)
	})
}

func TestResolver_CreateSchool_NoAdminToken(t *testing.T) {
	fmt.Println("\nRunning TestResolver_CreateSchool_NoAdminToken")
	c := helper.CreateClient()

	t.Run("Create school", func(t *testing.T) {

		err := c.Post(
			requests.CreateSchoolMutation,
			&r.CreateSchoolResponse,
			client.Var("input", requests.GenerateSchoolInput()),
			helper.AddContext(StudentToken),
		)

		assert.NotNil(t, err)

		var errorResponse []r.ErrorType
		err2 := json.NewDecoder(strings.NewReader(err.Error())).Decode(&errorResponse)
		assert.Nil(t, err2)

		assert.Equal(t, r.InvalidPermissionResponseError, errorResponse[0].Message)
	})
}
