package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"saga/graph/model"
	"saga/internal/auth"
)

// DeleteObject is the resolver for the deleteObject field.
func (r *mutationResolver) DeleteObject(ctx context.Context, filter *model.SagaFilter) (*model.SuccessMessage, error) {
	token := auth.TokenFromContext(ctx)

	sagaObject, err := r.Service.InitSagaSteps(token, filter)
	if err != nil {
		return nil, err
	}

	return sagaObject, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
